addons:
  chrome: stable
language: node_js
node_js:
  - "9.3.0"
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  ⋮
