# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - when:
          condition: $CIRCLE_BRANCH == develop
          steps:
            - run: echo "Branch is develop"
      - when:
          condition: false
          steps:
            - run: echo "Branch is master"
      - run:
          name: "Install missing library on awscli"
          command: sudo apt-get install -y libpython-dev
      - aws-cli/install
      - run: aws s3 ls

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
