# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      #Install AWS CLI
      # - run:
      #     name: "Install missing library on awscli"
      #     command: sudo apt-get install -y libpython-dev
      - aws-cli/install

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "develop" ]]; then
              yarn build:dev
              aws s3 sync dist s3://hop-web-test --delete
            fi
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              yarn build:prod
              aws s3 sync dist s3://hop-web --delete
            fi
